apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    app: nginx-np
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: web
    protocol: TCP
  selector:
    app: nginx-np
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-np
spec:
  selector:
    matchLabels:
      app: nginx-np
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-np
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: nginx-np
        image: nginx:1.7.9
        ports:
        - containerPort: 80
