apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx-headless
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-headless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-headless
spec:
  selector:
    matchLabels:
      app: nginx-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-headless
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: nginx-headless
        image: nginx:1.7.9
        ports:
        - containerPort: 80
